version: '3'
services:
  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8080"
  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - "8081:8080"
  wallet-service:
    build:
      context: ./wallet-service
    ports:
      - "8082:8080"