version: '3'
services:
  gateway:
    build:
      context: ./gateway
    ports:
      - 8083:8080
    container_name: gateway
    networks:
      - b-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  service-registry:
    build:
      context: ./service-registry
    ports:
      - 8761:8080
    container_name: service-registry
    networks:
      - b-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  notification-service:
    build:
      context: ./notification-service
    container_name: notification-service
    networks:
      - b-net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  transaction-service:
    build:
      context: ./transaction-service
    container_name: transactions-service
    networks:
      - b-net
    depends_on:
      - transactions-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  wallet-service:
    build:
      context: ./wallet-service
    container_name: wallet-service
    networks:
      - b-net
    depends_on:
      - wallet-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  transactions-db:
    image: mysql:${MYSQL_VERSION:-8.0.22}
    container_name: transactions-db
#    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - 33062:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-very_secret}
      MYSQL_DATABSE: ${DB_DATABASE:-transactions}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      - b-net
    volumes:
      - mysql-data:/var/lib/transactions-db
  wallet-db:
    image: mysql:${MYSQL_VERSION:-8.0.22}
    container_name: wallet-db
#    command: [ "--default-authentication-plugin=mysql_native_password" ]
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-very_secret}
      MYSQL_DATABSE: ${DB_DATABASE:-wallets}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    restart: unless-stopped
    networks:
      - b-net
    volumes:
      - mysql-data:/var/lib/wallets-db
  phpmyadmin-transactions:
    image: phpmyadmin
    restart: always
    ports:
      - 6072:80
    depends_on:
      - transactions-db
    environment:
      - PMA_HOST=transactions-db
    networks:
      - b-net
  phpmyadmin-wallets:
    image: phpmyadmin
    restart: always
    ports:
      - 6073:80
    depends_on:
      - wallet-db
    environment:
      - PMA_HOST=wallet-db
    networks:
      - b-net
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - b-net
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - b-net
volumes:
  mysql-data:
    driver: local
networks:
  b-net:
    driver: bridge
