version: '3'
services:
  service1:
    build:
      context: ./service-registry
    ports:
      - "8761:8080"
  service2:
    build:
      context: ./transaction-service
    ports:
      - "8081:8080"
  service3:
    build:
      context: ./wallet-service
    ports:
      - "8082:8080"